<<<<<<< HEAD
# Site settings
title: Lashi Bandara
description: "Lashi Bandara"
author: "Lashi Bandara"
header-img: img/background.jpg
profile-img: img/profile.jpg
email: lashi.bandara@brunel.ac.uk
baseurl: ""
url: "http://lashi-bandara.github.io"

# User accounts
twitter_username: pabryan78
github_username:  pabryan
facebook_username:  doctorpabryan
googleplus_username: PaulBryanguy
skype_username: paul_a_bryan
orcid: 0000-0001-8155-6091
arxiv_identifier: bryan_p_1
researchgate_username: Paul_Bryan3
googlescholar_username: buI6MKsAAAAJ
scirate_username: paul-bryan



#github_username: lashi-bandara
#facebook_username: lashputin
#skype_username: lashputin
#orcid: 0000-0003-1160-2261
#arxiv_identifier: bandara_l_1
#researchgate_username: Lashi-Bandara
#googlescholar_username: _D55D0sAAAAJ

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
=======
theme: jekyll-theme-cayman
>>>>>>> 46e8eb67f9f24a53bdca1a69b683bd9c59675be4
